### PR TITLE
doc: fix repo link

### PR DESCRIPTION
**Pull request by shawaj**
fix repo link to this repo

Change-type: patch
Signed-off-by: Aaron Shaw <shawaj@gmail.com>

### CODE REVIEW

**Comment by shawaj** [comment]
Also @seniorgod by the way - I dockerised this over here https://github.com/balenalabs/balena-sound/pull/399

Thought you might be interested.

**Comment by seniorgod** [comment]
thanks!

**Comment by shawaj** [comment]
@seniorgod are you able to control the volume using the tidal app on your phone/ computer using this?

I was able to but only if I run the speaker controller application in the bin directory.

**Comment by seniorgod** [comment]
I never tried out. 
I own a DAC with integrated analog volume control.
--

**Pull request merged**
